
enabled: true
backend: mne

event_source: annotations
event_mapping:
  left_hand: 2
  right_hand: 3

event_labels:
  left_hand: 0
  right_hand: 1

tmin: 0.0
tmax: 4.0
baseline: null

preload: true
reject_by_annotation: true

drop_last_incomplete_epoch: true
skip_missing_events: false

picks:
  - C3
  - Cz
  - C4