defaults:
  - _self_
  - raw_preprocessing: testing
  - paradigm: testing
  - epoch_preprocessing: testing
  - split: moabb_within_session
  - augmentation: basic
  - model: deep_learning/eegnet
  - metrics_aggregator: default
  - final_trainer: eegnet
  - evaluation: default
  - visualization: matplotlib
  - source: external
  - save_artifacts: default

mode: training
output_dir: ./outputs