name: "CI"

on:
  push:
    branches:
      - "feature/TMSPKED-380-CICD-Implement-CICD-Pipeline"
  pull_request:
    branches:
      - "feature/TMSPKED-380-CICD-Implement-CICD-Pipeline"

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Test Message
        run: echo "Ahoj světe

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
        
      - name: Print Python version
        run: python --version
      